#ifndef CHAINPARAMSSEEDS_H
#define CHAINPARAMSSEEDS_H
// List of fixed seed nodes for the bitcoin network
// AUTOGENERATED by contrib/devtools/generate-seeds.py

// Each line contains a 16-byte IPv6 address and a port.
// IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
static const unsigned int pnSeed[] =
{
  // 0x63ECD7E3, //215.227
  0xb2e9f3a2,
  0x1a04652e,
  0xa819cb9f,

};


static const unsigned int pnTestnetSeed[] = {

};
#endif
